"""rename address

Revision ID: d317fcfd9126
Revises: 371525eb37ba
Create Date: 2024-04-07 21:28:26.722547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd317fcfd9126'
down_revision = '371525eb37ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  
    new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  
    new_column_name='address')
    # ### end Alembic commands ###
